### Site Settings ###
title               : RYAN DAVIS
description         : >-
                      TECH & PIXEL ARTIST
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : DataIsGone/dataisgone.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
port: 4444


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/blog.html
  - pages/index.md
  - pages/pixelprojects.html


### Author Info ###
author:
  name              : Ryan Davis
  image             : /assets/img/common/ta_splash.gif
  email             : ryan.alex.davis@gmail.com
  github            : DataIsGone
  linkedin          : ryanalexdavis
  twitter           : dataisgone


### Posts ###
permalink: /pixelprojects/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /techart/:name

### Variables for Pixel Art Gallery ###
imagesurl: /art/img/
thumbsurl: /art/thumbs/

### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
