### Site Settings ###
title               : RYAN DAVIS
description         : >-
                      GRAPHICS | EXTENDED REALITY DEVELOPMENT
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : DataIsGone/dataisgone.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
port: 4444


### Plugins ###
# plugins:
#   - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/credits.html
  - pages/blog.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Ryan Davis
  image             : assets/img/testBio.png
# dribbble          : your_username
  email             : ryan.alex.davis@gmail.com
  github            : DataIsGone
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : ryanalexdavis
  twitter           : dataisgone
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
